version: '3.9'

services:
  nextjs:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  mock:
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "4000:4000"
    restart: always

  autotests:
    build:
      context: ./testBaseAutoTest
      dockerfile: Dockerfile
    depends_on:
      - nextjs
      - mock
    restart: "no"