version: '3.9'

services:
  nextjs:
    container_name: nextjs-app
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  mock:
    container_name: mock-server
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "4000:4000"
    restart: always

  autotests:
    container_name: autotests
    build:
      context: ./testBaseAutoTest
      dockerfile: Dockerfile
    depends_on:
      - nextjs
      - mock
    command: ["npm", "run", "test"]
    restart: "no"